### ISSUE TITLE
[Bug]: anyQuote nested quotes edge case, only with `inner`

### ISSUE THREAD

**Issue by tuurep** [chrisgrieser/nvim-various-textobjs#96] opened 2024-07-26 21:34 UTC
### Bug Description

When there are nested quotes, having the cursor on the first character of a nested quote and doing `.anyQuote("inner")`, the wrong quote gets matched (the outer nested quote).

This only concerns `.anyQuote("inner")`, with exact same cursor position and `.anyQuote("outer")`, it matches as expected (the inner nested quote).

The same happens when the cursor is on the opening quote of an inner nested quote, but I'm not 100% sure of the expected behavior in that case. `.anyQuote("outer")` from that position matches the inner nested quote however and it *feels* correct to me.

#### Before

```
"'foo' and ´bar´"
  ^
```

#### After `diq`

```
""
 ^
```

#### Expected

```
"'' and `bar`"
  ^
```

#### Before

```
"'foo' and ´bar´"
            ^
```

#### After `diq`

```
""
 ^
```

#### Expected

```
"'foo' and ``"
            ^
```

### neovim version

```Text
$ nvim --version
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1720049189
Run "nvim -V1 -v" for more info
```

**Comment by chrisgrieser** [comment] 2024-12-04 20:25
> ```
> "'foo' and ´bar´"
>   ^
> ```

This case has been fixed in one of the latest commits. (There was a remaining edge case if you are on the *ending* border of a nested text object, which I just fixed.)

> The same happens when the cursor is on the opening quote of an inner nested quote, but I'm not 100% sure of the expected behavior in that case. `.anyQuote("outer")` from that position matches the inner nested quote however and it feels correct to me.

Yeah, borders of nested textobjs are simply a bit tricky. With `inner`, only `foo` and `'foo' and bar` are the textobjects, and when you are exactly on the first `'`, you're technically standing on the inner `"`, but *in front* of the inner `'`. And in vim it's the idiomatic behavior that the text object you are standing on is always prioritized over text objects coming after the cursor (and this plugin tries to follow this behavior).

With `outer`, the objects are `'foo'` and `"'foo' and bar"`, and if you are on the first `'`, you are standing on two objects. In this case, the idiomatic vim behavior is to select the "more inner" object, so `'foo'` gets selected.

> ```
> "'foo' and ´bar´"
>             ^
> ```

This one does not work because it's forward-ticks (`´`) instead of backticks (`` ` ``), and the plugin only considers backticks (as forward-ticks are, to my knowledge, not used in programming).

If you meant to use backticks and just used forward-ticks to get it working in Markdown, then this is the same as the first case, which has been fixed in one of the later commits.

---

btw, you can write backticks `` ` `` in markdown inline code like this:
```
this in raw markdown: `` ` ``
results in this in rendered markdown: `
```

**Closed by chrisgrieser** 2024-12-04 20:25 UTC
Labels: bug

**Comment by tuurep** [comment] 2024-12-04 22:02
Thanks, it works and the explanation helps too

Haha, I'm quite confused where my forward-ticks came from, the example was meant to have backticks in each case

> btw, you can write backticks `` ` `` in markdown inline code like this...

Good to know, thanks!

**Comment by tuurep** [comment] 2024-12-04 22:34
Hmm, I notice problems however now with `.anyQuote("outer")`

Examples:

```
"'foo' and `bar`"
        ^
```

```
"'foo' and `bar`"
^
```

```
"'foo' and `bar`"
   ^
```

After `daq`, in all of the above the result is:

```
"
^
```

I wonder if this was introduced with [9905d24](https://github.com/chrisgrieser/nvim-various-textobjs/commit/9905d24c98dd6aee8161a64a6caff7786ad11b40), or if it's something I hadn't noticed before?

**Comment by chrisgrieser** [comment] 2024-12-05 01:02
yeah, I looked into it, and all those issues were a consequence of my (admittedly hacky) method to detect whether a quote is escaped or not without having lookbehinds in lua's regex.

Turns out, lua has something called frontier pattern, that can be used for a (small) lookbehind. And using that method, I think all the off-by-one issues you have noticed should be fixed now 😮‍💨

**Comment by tuurep** [comment] 2024-12-05 02:00
Great, others resolved, except for:

> ... leaves extra spaces compared to Vim's `da"`/`da'`/`` da` ``
>  - ```
>    "foo" 'bar' `baz`
>            ^
>    ```
>  - `daq`
>  - ```
>    "foo"  `baz`
>          ^
>    ```
>    (expected one less space)

**Comment by chrisgrieser** [comment] 2024-12-05 02:52
Yeah, that one is not a bug, but just how the plugin works. 

I'm not too sure about removing one of the surrounding spaces, since for consistency, I'd have to remove those spaces for either for all for none of the text objects by this plugin. And for a few, removing the spaces does not work well with how the textobj is designed. So making a decision is not straightforward. 

(vim itself is also not entirely consistent in this regard either, iirc.)

I'll have to think for a bit about that one.
